### ISSUE TITLE
Font on cookie banner is reverting to non standard

### ISSUE THREAD

**Issue by st3v3nhunt** [DEFRA/ffc-ahwr-backoffice#9]
The font isn't correct, see:
![Screenshot 2022-06-22 at 12 37 35](https://user-images.githubusercontent.com/639706/175020128-815840d0-5891-4338-bbb2-8dc336329f36.png)

It should look like the version from `ffc-ahwr-frontend`:
![Screenshot 2022-06-22 at 12 39 00](https://user-images.githubusercontent.com/639706/175020285-983468d6-d3bc-4aea-843f-895f4a1ed408.png)

**Comment by govTechSatish** [comment]
Fix release in 1.4.1
